services:
  mongodb:
    image: mongo:7-jammy
    container_name: mngodb
    ports:
      - "27007:27017"
    volumes:
      - ./mngodb:/data/db
    networks:
      - backend
    restart: always

networks:
  backend:
    